services:
  - type: web
    name: oasis-game
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_DB_PATH
        value: data/db.json
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_TOKEN
        sync: false
